CarRenting/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from car_renting import views as car_renting_views

urlpatterns = [
    path('', include('accounts.urls')),
    path('car_renting/', include('car_renting.urls')),
    path('admin/', admin.site.urls),    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.user_login),
    path('login', views.user_login, name='login'),
    path('userregistration', views.user_registration, name='registration'),
    path('logout', views.user_logout, name='logout'),
    path('settings', views.settings, name="settings"),
    path('update/user/passowrd/<int:id>', views.update_password, name="password_update"),
    path('update/user/profile/<int:id>', views.update_profile, name="profile_update")
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from time import strftime, gmtime
from django.utils import timezone
from django.conf import settings
from django.core.mail import send_mail
from django.db.utils import IntegrityError
from django.core.exceptions import ValidationError


class CustomManager(BaseUserManager):
    def _create_user(self, email=None, password=None, is_superuser=False, is_staff=False, is_active=False):
        if email is None:
            raise ValueError("users must have an email")
        if password is None:
            raise ValueError("users must have a password")

        user = self.model(
            email=self.normalize_email(email),
            is_superuser=is_superuser,
            is_staff=is_staff,
            is_active=is_active,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **kwargs):
        user = self._create_user(
            email, password, is_staff=False, is_superuser=False, is_active=False)
        user.first_name = kwargs['first_name']
        user.last_name = kwargs['last_name']
        user.date_joined = strftime("%Y-%m-%d %H:%M:%S", gmtime())
        user.save(using=self._db)
        return user

    def create_staffuser(self, email=None, password=None, **kwargs):
        user = self._create_user(
            email, password, is_staff=True, is_superuser=False, is_active=False)
        user.first_name = kwargs['first_name']
        user.last_name = kwargs['last_name']
        user.date_joined = strftime("%Y-%m-%d %H:%M:%S", gmtime())
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **kwargs):
        user = self._create_user(
            email, password, is_superuser=True, is_staff=True, is_active=True)
        user.first_name = kwargs['first_name']
        user.last_name = kwargs['last_name']
        user.date_joined = strftime("%Y-%m-%d %H:%M:%S", gmtime())
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    date_joined = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name',]

    users = CustomManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_short_name(self):
        return self.last_name

    def get_username(self):
        return self.email


class UserProfile(models.Model):

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    mobile_contact = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    date_of_birth = models.DateField(blank=True, null=True)
    profile_image = models.ImageField(upload_to='users/images/%Y/%M/%d', blank=True, null=True, default='users/user.png')

    # number of cars a user has ever booked
    booked_cars = models.IntegerField(default=0)

    # number of cars a user owns/registered as his in the system
    owned_cars = models.IntegerField(default=0)

    profiles = models.Manager()

    def __str__(self):
        return self.user.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import *
from car_renting.models import Car


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = CustomUser.users.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name')


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('mobile_contact', 'location', 'date_of_birth', 'profile_image')


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = ('email', 'password')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', 'password')


class PasswordReset(forms.Form):
    email = forms.EmailField()

    class Meta:
        model = CustomUser
        fields = ('email',)


class Newpassword(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ()

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2


#############   CAR RENTING APP FORMS ############
# these forms are declared here because i am curently working on a dead line

class NewCarForm(forms.ModelForm):
    
    class Meta:
        model = Car
        fields = ()

accounts/views.py
from django.shortcuts import render, get_object_or_404
from . import forms
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, views
from .models import *
from django.contrib.auth import logout
from car_renting.models import Notification


# this variable is created due to an error that settings has no 
# variable static url, (setting has a variable called STATIC_URL though)
# for some reasons i did not have time to fix this is the teporary fix
STATIC_URL = '/static/'
MEDIA_URL = '/media/'


def user_login(request):
    fresh_form = forms.LoginForm()
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                username=data['email'], password=data['password'])
            if user is not None:
                if user.is_active:
                    request.session['username'] = user.email
                    login(request, user)
                    return redirect('/car_renting/home')
                else:
                    context = {
                        'with_status' : True,
                        'title': 'Failed!!',
                        'info' : 'account disabled',
                        'static_url': STATIC_URL,
                        'alert': 'alert-danger'
                    }
                    return render(request, 'login.html', context)
            else:
                context = {
                    'with_status' : True,
                    'title': 'Failed!!',
                    'info' : 'invalid user name or password',
                    'static_url': STATIC_URL,
                    'alert': 'alert-danger'
                }
                return render(request, 'login.html', context)
        else:
            context = {
                'with_status' : True,
                'title': 'Failed!!',
                'info' : 'invaild data provided',
                'static_url': STATIC_URL,
                'alert': 'alert-danger'
            }
            return render(request, 'login.html', context)
    else:
        static_url = STATIC_URL

        # if user is authenticated bypass the login page
        if request.user.is_authenticated:
            return redirect('/car_renting/home')
            
        return render(request, 'login.html', {'form': fresh_form, 'static_url': static_url})


def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('/login')
    else:
        return redirect('/login')

def user_registration(request):

    if request.method == 'POST':
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True
            user.set_password(form.cleaned_data['password2'])
            user.save()

            new_user = UserProfile(user=user)
            new_user.save()

            context = {
                'with_status' : True,
                'title': 'Success',
                'info' : 'you have successfully registered',
                'alert': 'alert-success',
                'static_url': STATIC_URL
            }
            return render(request, 'Registration/register.html', context)
        else:
            context = {
                'with_status' : True,
                'title': 'Failed',
                'info' : 'Invalid data provided, please check your input',
                'static_url': STATIC_URL,
                'alert': 'alert-danger'
            }
            return render(request, 'Registration/register.html', context)
    else:
        form = forms.RegisterForm()
        static_url = STATIC_URL
        return render(request, 'Registration/register.html', {"form": form, 'static_url': static_url})


def settings(request):
    if request.user.is_authenticated:
        if request.method == "GET":
            # check for unread notifications
            notifications = Notification.notifications.filter(target__id=request.user.id).order_by('-created_at')
            navbar_notifications = notifications.filter(is_viewed=False)

            context = {
                'user': request.user,
                'view_type': 'settings',
                'navbar_notifications': navbar_notifications,

                'media': MEDIA_URL,
                'static_url': STATIC_URL,
                'form': forms.UserProfileUpdateForm
            }
            return render(request, 'home.html', context)

        elif request.method == "POST":
            form = forms.UserUpdateForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                return redirect('/settings')
            else:
                return redirect('/settings')
    else:
        return redirect('/login')


def update_password(request, id):

    if request.method == "POST":
        user = get_object_or_404(CustomUser, pk=id)
        form = forms.Newpassword(request.POST, instance=user)
        if form.is_valid():
            user.set_password(form.cleaned_data['password2'])
            user.save()
            return redirect('/settings')
        else:
            return redirect('/settings')


def update_profile(request, id):

    if request.method == "POST":
        profile = get_object_or_404(UserProfile, pk=id)
        form = forms.UserProfileUpdateForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('/settings')
        else:
            print(form.data)
            return redirect('/settings')

accounts/templates/home.html
{% extends "index.html" %}
{% load static %}

{% block homecontent %}
  {% include 'common/sidebar.html' %}
  <div class="main-content">
      {% include 'common/navbar.html' %}

      {% if view_type == 'home' %}
          {% include 'landingpage.html' %}

      {% elif view_type == 'car_details' %}
        {% include 'cardetails.html' %}

      {% elif view_type == 'notifications' %}
        {% include 'notification.html' %}

      {% elif view_type == 'profile' %}
        {% include 'userprofile.html' %}
      
      {% elif view_type == 'account' %}
        {% include 'account.html' %}
      
      {% elif view_type == 'settings' %}
        {% include 'settings.html' %}

      {% elif view_type == 'page_not_found' %}
        {% include 'common/notfound.html' %}
      
      {% elif view_type == 'payments' %}
        {% include 'payments.html' %}
        
      {% endif %}
  </div>
{% endblock %}

accounts/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="The premier performance rally championship in Tanzania, and a number of 
    regional rally championships from coast-to-coast">
    
    <script>
        var colorScheme = ( localStorage.getItem('dashkitColorScheme') ) ? localStorage.getItem('dashkitColorScheme') : 'light';
    </script>
    {% include 'includes/csslinks.html' %}
    <title>CRMS</title>
  </head>
  <body>
      {% block homecontent %}{% endblock %}
    <div class="container">
      {% block authenticationpage %}{% endblock %}
    </div>
    {% include 'includes/jslinks.html' %}
  </body>
</html>

accounts/templates/login.html
{% extends "index.html" %}
{% load static %}

{% block authenticationpage %}
<div class="container-fluid mt-5 pt-5">
    <div class="row align-items-center">
        <div class="col-12 col-md-6 offset-xl-2 offset-md-1 order-md-2 mb-5
            mb-md-0">
        
            <!-- Image -->
            <div class="text-center">
                <img src="{{ static_url }}assets/img/illustrations/happiness.svg"
                    alt="..." class="img-fluid">
            </div>
        </div>
        <div class="col-12 col-md-5 col-xl-4 order-md-1 my-5">

            <!-- Heading -->
            <h1 class="display-4 text-center mb-3">
                Sign In
            </h1>
            <!-- Subheading -->
            <p class="text-muted text-center mb-5">
                Free access to our dashboard.
            </p>
            <!-- Form -->
            <form action='#' method='post'>

                {% if with_status %}
                    <div class="alert {{ alert }} alert-dismissible fade show" role="alert">
                        <strong>{{ title }}</strong> {{ info }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                {% endif %}
                {% csrf_token %}
                <!-- Email address -->
                <div class="form-group">
                    <!-- Label -->
                    <label>
                        Email Address
                    </label>
                    <!-- Input -->
                    <input type="email" name="email" maxlength="254" required=""
                        id="id_email" class="form-control"
                        placeholder="name@address.com">
                </div>
                <!-- Password -->
                <div class="form-group">
                    <!-- Label -->
                    <label>
                        Password
                    </label>
                    <!-- Input group -->
                    <div class="input-group input-group-merge">
                        <!-- Input -->
                        <input type="password" name="password" required=""
                            id="id_password" class="form-control
                            form-control-appended" placeholder="Enter your password">
                        <!-- Icon -->
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fe fe-eye"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <!-- Submit -->
                <button class="btn btn-lg btn-block btn-dark mb-3">
                    Sign in
                </button>
                <!-- Link -->
                <div class="text-center">
                    <small class="text-muted text-center">
                        Dont have an account? <a href="{% url 'registration' %}">Register</a>.
                    </small>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/settings.html
<div class="container-fluid">
    <div class="row">
        <div class="col-12">

            <!-- Header -->
            <div class="header mt-md-5">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">

                            <!-- Pretitle -->
                            <h6 class="header-pretitle">
                                {{ request.user.email }}
                            </h6>

                            <!-- Title -->
                            <h1 class="header-title">
                                Profile Settings
                            </h1>

                        </div>
                    </div> <!-- / .row -->
                    <div class="row align-items-center">
                        <div class="col">

                            <!-- Nav -->
                            <ul class="nav nav-tabs nav-overflow header-tabs">
                                <li class="nav-item">
                                    <a href="#!" class="nav-link active">
                                        General
                                    </a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row justify-content-between p-5">
                <div class="col-md-5 mb-5">
                    <form action='#' method='post'>

                        {% if with_status %}
                        <div class="alert {{ alert }} alert-dismissible fade
                            show" role="alert">
                            <strong>{{ title }}</strong> {{ info }}
                            <button type="button" class="close"
                                data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        {% endif %}

                        {% csrf_token %}
                        <!-- Email address -->
                        <div class="form-group">
                            <!-- Label -->
                            <label>
                                Email Address
                            </label>
                            <!-- Input -->
                            <input type="email" name="email" maxlength="254"
                                required=""
                                id="id_email" class="form-control" value="{{ request.user.email }}"
                                placeholder="name@address.com">
                        </div>
                        <div class="form-group">
                            <!-- Label -->
                            <label>
                                First name
                            </label>
                            <!-- Input -->
                            <input type="text" name="first_name" maxlength="60"
                                required="" value="{{ request.user.first_name }}"
                                id="id_first_name" class="form-control"
                                placeholder="first name">
                        </div>
                        <div class="form-group">
                            <!-- Label -->
                            <label>
                                Last name
                            </label>
                            <!-- Input -->
                            <input type="text" name="last_name" maxlength="60"
                                required="" value="{{ request.user.last_name }}"
                                id="id_last_name" class="form-control"
                                placeholder="last name">
                        </div>
                        <!-- Submit -->
                        <button class="btn btn-lg btn-block btn-dark mb-3">
                            update info
                        </button>
                    </form>
                </div>
                <div class="col-md-5 mb-5">
                    <form action="{% url 'password_update' request.user.id %}" method='post'>

                        {% if with_status %}
                        <div class="alert {{ alert }} alert-dismissible fade
                            show" role="alert">
                            <strong>{{ title }}</strong> {{ info }}
                            <button type="button" class="close"
                                data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        {% endif %}

                        {% csrf_token %}
                        <!-- Email address -->
                        <div class="form-group">
                            <!-- Label -->
                            <label>
                                New Password
                            </label>
                            <!-- Input group -->
                            <div class="input-group input-group-merge">
                                <!-- Input -->
                                <input type="password" name="password1"
                                    required=""
                                    id="id_password1" class="form-control
                                    form-control-appended" placeholder="Enter your password">
                                <!-- Icon -->
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fe fe-eye"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <!-- Label -->
                            <label>
                                Confirm Password
                            </label>
                            <!-- Input group -->
                            <div class="input-group input-group-merge">
                                <!-- Input -->
                                <input type="password" name="password2"
                                    required=""
                                    id="id_password2" class="form-control
                                    form-control-appended" placeholder="Confirm
                                    your password">
                                <!-- Icon -->
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fe fe-eye"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <!-- Submit -->
                        <button class="btn btn-lg btn-block btn-dark mb-3">
                            Change Password
                        </button>
                    </form>
                </div>
                <div class="col-md-5 mb-5">   
                    <form enctype="multipart/form-data" action="{% url 'profile_update' request.user.userprofile.id %}" method='post'>

                        {% if with_status %}
                        <div class="alert {{ alert }} alert-dismissible fade
                            show" role="alert">
                            <strong>{{ title }}</strong> {{ info }}
                            <button type="button" class="close"
                                data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        {% endif %}

                        {% csrf_token %}

                        <!-- Email address -->
                        <div class="form-group">
                            <!-- Label -->
                            <label>
                                Location
                            </label>
                            <!-- Input -->
                            <input type="text" name="location" maxlength="255" required="" id="id_location"
                             class="form-control" value="{{ request.user.userprofile.location }}"
                                placeholder="location">
                        </div>
                        <div class="form-group">
                            <!-- Label -->
                            <label>
                                Date of Birth
                            </label>
                            <!-- Input -->
                            <input type="text" name="date_of_birth" maxlength="60"
                                required="" value="{{ request.user.userprofile.date_of_birth|date:'Y-m-d' }}"
                                id="id_date_of_birth" class="form-control"
                                placeholder="year-month-date">
                        </div>
                        <div class="form-group">
                            <!-- Label -->
                            <label>
                                Mobile Contact
                            </label>
                            <!-- Input -->
                            <input type="text" name="mobile_contact" maxlength="255" required="" id="id_mobile_contact"
                                value="{{ request.user.userprofile.mobile_contact }}" class="form-control" placeholder="(+255)-xxx-xxx-xxx">
                        </div>
                       <div class="col-12 mb-3">
                            <!-- First name -->
                            <div class="form-group">
                            <!-- Label -->
                            <label>
                                Cover Photo
                            </label>
                            <!-- Input -->
                            <input type="file" class="form-control" style="border: none; background: transparent;"
                                name="profile_image" accept="image/*" id="id_profile_image">
                            </div>
                        </div>
                        <!-- Submit -->
                        <button class="btn btn-lg btn-block btn-dark mb-3">
                            update info
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>